config/routes.rb
Rails.application.routes.draw do
  resources :games do
    member do
      post :join
    end

    resources :moves, only: %i[create]
  end

  get "/auth/google/callback" => "sessions#create"
  get "/logout" => "sessions#destroy", as: :logout
  get "/login" => "sessions#new", as: :login

  root to: "games#index"

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players, dependent: :destroy
  has_many :users, through: :players
  has_many :turns, inverse_of: :game, dependent: :destroy
  has_many :moves, through: :turns

  enum state: {
    waiting_for_players: "waiting_for_players",
    playing: "playing",
    finished: "finished"
  }

  validates :board_shape, :board_size,
    presence: true
  validates :board_size,
    numericality: { only_integer: true, greater_than: 0 }
  validates :starting_player_position,
    inclusion: {
      in: ->(game) { game.players.map(&:position) },
      allow_blank: true
    }

  scope :open, -> { where("players_count < 2") }
  scope :oldest_first, -> { order(created_at: :asc) }

  def board
    @board ||= Board.new(shape)
  end

  def number_of_colors
    4
  end

  def maximum_number_of_players
    2
  end

  def full?
    players.count >= maximum_number_of_players
  end

  def open?
    players.count < maximum_number_of_players
  end

  def colors
    @colors ||= Color.first(number_of_colors)
  end

  def shape
    Board.const_get(board_shape.to_s.camelize).new(board_size)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  helper_method :current_player

  def index
    @games = GamesForUser.new(current_user).games
  end

  def show
    @game_presenter = GamePresenter.new(game, current_user)
  end

  def create
    CreateGame.new(current_user)
      .on(:success) do |game|
        self.current_player = game.players.first
        redirect_to games_path
      end
      .on(:failure) { |game| render :new }
      .call
  end

  def join
    JoinGame.new(current_user, game)
      .on(:success) do |player|
        self.current_player = player
        redirect_to game
      end
      .on(:already_playing, :full) { redirect_to games_path }
      .on(:failure) { |_| redirect_to games_path }
      .call
  end

  def destroy
    game.destroy
    redirect_to games_path
  end

  private

  def game
    @game ||= Game.includes(turns: :moves).find(params[:id])
  end

  def current_player
    @player ||= game.players.detect do |player|
      player.user_id == current_user.id
    end
  end

  def current_player=(player)
    @player = player
    cookies.signed[:user_id] = current_user.id
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def playing?(game, user = current_user)
    game.players.any? { |player| player.user_id == user.id }
  end

  def other_players(game, user = current_user)
    game.players.reject { |player| player.user_id == user.id }
  end

  def whose_turn(player)
    if player.user_id == current_user.id
      t("games.show.your_turn")
    else
      t("games.show.their_turn", opponent: player)
    end
  end

  def meta_tags(values)
    values.each do |name, content|
      concat meta_tag(name, content)
    end
  end

  def winning_message(player)
    content = if player.user_id == current_user.id
      t("games.result.you_win")
    else
      t("games.result.they_win", player: player.name)
    end

    content_tag :p, content, class: "winner", "data-player-id" => player.id
  end

  private

  def meta_tag(name, content)
    content_tag :meta, nil, name: name, content: content
  end
end

app/views/games/_game.html.haml
%li.game
  - if game.full?
    = link_to t("games.index.playing_with", players: other_players(game).to_sentence), game
  - elsif playing?(game)
    = t("games.index.waiting")
    = link_to t("games.index.cancel"), game, method: :delete
  - else
    = link_to t("games.index.join_with", players: other_players(game).to_sentence), join_game_path(game), method: :post

app/views/games/_games.html.haml
- if games.any?
  %ul.games
    = render games
- else
  %p.empty= t("games.index.nothing")

app/views/games/_result.html.haml
.game-result{class: ("show" if game.finished?)}
  %h2= t(".game_over")
  - game.players.each do |player|
    = winning_message(player)

app/views/games/index.html.haml
%header
  %h1= t(".title")
%main.games-list
  %section.my-games
    %h2= t(".in_progress")
    = render partial: "games", object: @games.select(&:full?)
    = link_to t(".create"), games_path, method: :post, class: "button"
  %section.waiting-games
    %h2= t(".waiting")
    = render partial: "games", object: @games.select(&:open?)

app/views/games/show.html.haml
- content_for :head do
  - meta_tags "player-id" => current_player.id, "game-id" => @game_presenter.id
  = javascript_include_tag "game"

%header
  = link_to games_path do
    = icon("chevron-left")
    = t(".back")
  %ul.scores
    %li{"data-player-id": @game_presenter.player.id}
      %span.name= t(".you")
      %b.score= @game_presenter.player.score
    %li{"data-player-id": @game_presenter.opponent.id}
      %span.name= @game_presenter.opponent
      %b.score= @game_presenter.opponent.score
  %span.turn= whose_turn(@game_presenter.current_player)

%main
  = board @game_presenter.board

= palette @game_presenter
= render "result", game: @game_presenter